### ISSUE TITLE
"vchrisb/setup-cf@v1" showing error in deploy-to-prd.yml File

### ISSUE THREAD

**Issue by upndown4par522** [vchrisb/setup-cf#9]
Starting a couple of days ago, in my deploy-do-prd.yml file, I have this code:

- name: Set up CF
        uses: vchrisb/setup-cf@v1
        with:
          api: ${{ secrets.CF_API }}
          username: ${{ secrets.CF_USERNAME }}
          password: ${{ secrets.CF_PASSWORD }}
          org: dev-learning-trial
          space: I869223

vchrisb/setup-cf@v1 is showing this error in vs code:  Unable to resolve action `vchrisb/setup-cf@v1`, repository or version not found

Any ideas and/or suggestions would be greatly appreciated.

**Comment by vchrisb** [comment]
The tag is available: https://github.com/vchrisb/setup-cf/releases/tag/v1

**Comment by upndown4par522** [comment]
Hi Chris,

Thank you for your response.   I downloaded the source code, saved it to a folder on my computer and opened it with VS Code.

I'm so new at this that I'm not sure what to do with it.  Do I need to push it to GitHub?  If so, what repository and branch?

I'm using the SAP Enterprise version of GitHub.

Sorry for the newbie questions but that's how green I am with this type of development.  LOL

Any suggestions and/or recommendations you could make would be fantastic.

Thanks again!

Ron

**Comment by vchrisb** [comment]
The action will be pulled automatically when you are using it in your workflow. 
You need to add a step like:

```
steps:
- uses: actions/checkout@v4
- uses: vchrisb/setup-cf@v1
  with:
    api: ${{ secrets.CF_API }}
    username: ${{ secrets.CF_USERNAME }}
    password: ${{ secrets.CF_PASSWORD }}
    org: test
    space: dev
- name: run cf command
  run: cf apps
```

Some more general information on writing Github workflows: https://docs.github.com/en/actions/writing-workflows/quickstart
